#!/bin/sh

mode=$1

if [ "$mode" != "0" ] && [ "$mode" != "1" ]; then echo "mode is not recognized. abort."; exit 1; fi

run=$2

atms=$3

w1=$5
w2=$6

st=$7
en=$8

name=$4:$en

#wt=24:00:00
#wt=48:00:00
wt=72:00:00

ncpus=1

mem=2gb

base=/rds/general/user/rtagirov/ephemeral/runs/nessy

rm -f $base/$run/fail.log
rm -f $base/$run/spec.out

qsub -v \
mode=$mode,\
run=$run,\
atms=$atms,\
w1=$w1,\
w2=$w2 \
-J $st-$en:1 \
-o $HOME/log/$JOB_ID \
-e $HOME/log/$JOB_ID \
-N $name \
-lwalltime=$wt \
-lselect=1:ncpus=$ncpus:mem=$mem:avx2=true calc_ray_spec
