      module MOD_DELTAGR
      contains
      FUNCTION DELTAGR(R)
C***  DIFFERENCE OF VELOCITY GRADIENTS FROM BOTH VELOCITY LAWS:
C***  THE BETA LAW (OUTER REGION) AND THE EXPONENTIAL LAW (INNER REGION)
C***  THIS ROUTINE SERVES FOR ESTIMATING THE CONNECTION POINT BETWEEN BOTH
C***  REGIONS AND IS CALLED FROM SUBROUTINE INITVEL, MAIN PROGRAM WRSTART

      IMPLICIT REAL*8(A-H,O-Z)
     
      PARAMETER ( ONE = 1.D+0, TWO = 2.D+0 )
      
      COMMON/VELPAR/ VFINAL,VMIN,BETA,VPAR1,VPAR2,RCON,HSCALE
      COMMON/VELPA1/ RMA
     
C***  ASSUMING THAT R IS THE CONECTION RADIUS
      VCON=VMIN/R/R*EXP((ONE-ONE/R)/HSCALE)
      Q=(VCON/VFINAL)**(ONE/BETA)
      VPAR2=(ONE-Q)/(ONE/R - Q/RMA)
      VPAR1=VCON/(ONE-VPAR2/R)**BETA
      DELTAGR=VPAR1*VPAR2*BETA*(ONE-VPAR2/R)**(BETA-ONE)/R/R -
     -        VMIN/R/R*EXP((ONE-ONE/R)/HSCALE)*(ONE/R/R/HSCALE-TWO/R)
      RETURN
      END function
      end module