      MODULE HMINUS_COMMONS
      
!       use PARAMS_ARRAY
!       real*8 :: RADIUS(NDDIM),ENTOT(NDDIM),T(NDDIM)
!       real*8 :: XJC(NDDIM),XJCARR(NDDIM,NFDIM),XJL(NDDIM,MAXIND)
!       real*8 :: EDDI(3,NDDIM),EDDARR(3,NDDIM,NFDIM),TAUROSS(NDDIM)
      END MODULE
!       
!       MODULE HMINUS_COMMONS_LIBLFAC
!       use PARAMS_ARRAY
!       real*8 :: SCAFAC(NDDIM,NFDIM),ABSFAC(NDDIM,NFDIM)
!       END MODULE
