#!/bin/bash

export N_sub=1

reverse_cube_frac=32

#submit_split_cube lte  G2V hydro 123_lte  123_wcr
#submit_split_cube lte  G2V 300G  118_lte  118_wcr

#submit_split_cube nlte G2V hydro 123_nlte 123_wcr
#submit_split_cube nlte G2V 300G  118_nlte 118_wcr

#------------------------------------------------------

#submit_split_cube lte  G2V hydro 123_lte_eh  123_wcr
#submit_split_cube lte  G2V 300G  118_lte_eh  118_wcr

#submit_split_cube nlte G2V hydro 123_nlte_eh 123_wcr
#submit_split_cube nlte G2V 300G  118_nlte_eh 118_wcr

#-------------------------------------------------------

#submit_split_cube nlte G2V hydro 123_nlte_eh 123_wcr

#-------------------------------------------------------

#submit_split_cube lte  G2V ssd 186_lte  186_wcr
#submit_split_cube nlte G2V ssd 186_nlte 186_wcr

#-------------------------------------------------------

#submit_split_cube lte  G2V hydro 123_lte_mu_08  123_wcr_mu_08
#submit_split_cube lte  G2V 300G  118_lte_mu_08  118_wcr_mu_08

#submit_split_cube nlte G2V hydro 123_nlte_mu_08 123_wcr_mu_08
#submit_split_cube nlte G2V 300G  118_nlte_mu_08 118_wcr_mu_08

#------------------------------------------------------

#submit_split_cube G2V hydro 8 angles nlte 6 mu/6
#submit_split_cube G2V 300G  8 angles nlte 6 mu/6

#submit_split_cube G2V hydro 8 angles lte  6 mu/6
#submit_split_cube G2V 300G  8 angles lte  6 mu/6

#submit_split_cube G2V ssd   8 angles nlte 8 mu/8
#submit_split_cube G2V ssd   8 angles nlte 6 mu/6

#submit_split_cube G2V ssd   8 angles lte  8 mu/8
#submit_split_cube G2V ssd   8 angles lte  6 mu/6

#------------------------------------------------------

#nessy_submit_split_cube G2V 300G  8 angles lte  2 mu/atms/nessy/2
#nessy_submit_split_cube G2V ssd   8 angles lte  2 mu/atms/nessy/2
#nessy_submit_split_cube G2V hydro 8 angles lte  2 mu/atms/nessy/2

#nessy_submit_split_cube G2V 300G  8 angles nlte 2 mu/atms/nessy/2
#nessy_submit_split_cube G2V ssd   8 angles nlte 2 mu/atms/nessy/2
#nessy_submit_split_cube G2V hydro 8 angles nlte 2 mu/atms/nessy/2

#------------------------------------------------------

#s=103833

#nessy_submit_split_cube G2V 300G  8 $s lte 2 $s/mu/atms/nessy/2
#nessy_submit_split_cube G2V 300G  8 $s lte 4 $s/mu/atms/nessy/4
#nessy_submit_split_cube G2V 300G  8 $s lte 6 $s/mu/atms/nessy/6
#nessy_submit_split_cube G2V 300G  8 $s lte 8 $s/mu/atms/nessy/8
#nessy_submit_split_cube G2V 300G  8 $s lte 1 $s/mu/atms/nessy/1

#s=251568

#nessy_submit_split_cube G2V ssd   8 $s lte 2 $s/mu/atms/nessy/2
#nessy_submit_split_cube G2V ssd   8 $s lte 4 $s/mu/atms/nessy/4
#nessy_submit_split_cube G2V ssd   8 $s lte 6 $s/mu/atms/nessy/6
#nessy_submit_split_cube G2V ssd   8 $s lte 8 $s/mu/atms/nessy/8
#nessy_submit_split_cube G2V ssd   8 $s lte 1 $s/mu/atms/nessy/1

#s=235427

#nessy_submit_split_cube G2V hydro 8 $s lte 2 $s/mu/atms/nessy/2
#nessy_submit_split_cube G2V hydro 8 $s lte 4 $s/mu/atms/nessy/4
#nessy_submit_split_cube G2V hydro 8 $s lte 6 $s/mu/atms/nessy/6
#nessy_submit_split_cube G2V hydro 8 $s lte 8 $s/mu/atms/nessy/8
#nessy_submit_split_cube G2V hydro 8 $s lte 1 $s/mu/atms/nessy/1

#--------------------------------------------------------

#rmode=(nlte)
rmode=(lte)

#ctype=(300G ssd hydro)
#ctype=(300G ssd)
#ctype=(300G)
ctype=(ssd)
#ctype=(hydro)

#csnap=(118000 186000 123000)
#csnap=(627321 222809 214519)
#csnap=(627321 222809)
#csnap=(627321)
csnap=(222809)
#csnap=(214519)

#rangl=(2 4 6 8 10)
#rangl=(2 4 6 8)
#rangl=(10)
rangl=(2)
#rangl=(6)
#rangl=(8)
#rangl=(2 10)
#rangl=(4)

lrmode=${#rmode[@]}-1
lctype=${#ctype[@]}-1
lrangl=${#rangl[@]}-1

for ((j=0; j<=$lrangl; j+=1)); do

    for ((k=0; k<=$lrmode; k+=1)); do

        for ((i=0; i<=$lctype; i+=1)); do

#            nessy_submit_split_cube_hk G2V ${ctype[i]} ${csnap[i]} $reverse_cube_frac 246810 ${rmode[k]} ${rangl[j]} ${rangl[j]}/atms/nessy housekeeping
            nessy_submit_split_cube_hk G2V ${ctype[i]} ${csnap[i]} $reverse_cube_frac 246810 ${rmode[k]} ${rangl[j]} ${rangl[j]}/atms/nessy original_run

        done

    done

done
