#!/bin/bash

if [ $# != 9 ]; then
 
   echo expecting 9 arguments: stype, ctype, csnap, reverse_cube_frac, N_groups, rmode, rangl, spath, regime
 
   exit 1
 
fi

declare -i reverse_cube_frac

stype=$1 # spectral type
ctype=$2 # cube type
csnap=$3 # cube snapshot id
reverse_cube_frac=$4 # reverse of the fraction of the cube to be calculated
N_groups=$5 # number of groups for housekeeping run
rmode=$6 # lte or nlte
rangl=$7 # run angle (index of the cube inclination)
spath=$8 # path to cube slices
regime=$9 # original_run or housekeeping (calculating spectra left over after the main run)

if [ $rmode != lte ] && [ $rmode != nlte ]; then

    echo "rmode not recognized. abort."

    exit 1

fi

if [[ $HOME == /rds/general/user/rtagirov/home ]]; then

    host=imperial

elif [[ $HOME == /home/dc-tagi1 ]] && [[ $(hostname) == *dirac* ]]; then

    host=dirac_leicester

elif [[ $HOME == /home/dc-tagi1 ]] && [[ $(hostname) == *login* ]]; then

    host=dirac_cambridge

else

    echo "Host not recognized. Abort."

    exit 1

fi

if [ $host == imperial ]; then

    rds=/rds/general/user/rtagirov/ephemeral

    base=$rds/runs/nessy

    pca_mode=TmaxPmaxDmax

#    atm=$HOME/cubes/matthias/$ctype/$csnap/$spath
#    atm=$rds/cubes/veronika/$stype/$ctype/$csnap/$spath
#    atm=$HOME/cubes/veronika/$stype/$ctype/$csnap/$spath
#    atm=$rds/cubes/blake/$stype/$ctype/$csnap/$spath

#    atm=$rds/cubes/$pca_mode/$stype/$ctype/$csnap/$spath
    atm=$rds/cubes/tanayveer/$stype/$ctype/$csnap/$spath

#    IFS='/' read -r -a array <<< $spath

#    csnap=${array[-1]}

#    echo $csnap

#    exit 0

#    run=veronika/$stype/$ctype/$csnap/$reverse_cube_frac/$rname/$rmode/$rangl
#    run=veronika/$stype/$ctype/$csnap/$rmode/$rangl
#    run=veronika/$stype/$ctype/$csnap/$reverse_cube_frac/$rmode/$rangl
#    run=test_run/$stype/$ctype/$csnap/$reverse_cube_frac/$rmode/$rangl

#    run=$pca_mode/$stype/$ctype/$csnap/$reverse_cube_frac/$rmode/$rangl
    run=tanayveer/$stype/$ctype/$csnap/$reverse_cube_frac/$rmode/$rangl

    nes=$HOME/nessy

    scr=$nes/scr
    obj=$nes/obj
    inp=$nes/inp

elif [ $host == dirac_leicester ]; then

    rds=/scratch/dp100/dc-tagi1

#    base=$rds/runs/nessy
    base=$rds/runs

#    atm=$rds/cubes/matthias/$ctype/$csnap/$spath
    atm=$rds/cubes/veronika/$stype/$ctype/$csnap/$spath

#    run=veronika/$stype/$ctype/$csnap/$reverse_cube_frac/$rname/$rmode/$rangl
#    run=veronika/$stype/$ctype/$csnap/$rangl
#    run=test_run_8_jobs/$stype/$ctype/$csnap/$rangl
    run=test_pmem/$stype/$ctype/$csnap/$rangl
#    run=$stype/$ctype/$csnap/$rangl

#    scr=$HOME/nessy/scr
#    obj=$HOME/nessy/obj
#    inp=$HOME/nessy/inp

    nes=$rds/nessy

    scr=$nes/scr
    obj=$nes/obj
    inp=$nes/inp

elif [ $host == dirac_cambridge ]; then

    rds=/home/dc-tagi1/rds/rds-dirac-dp100-n0fcCTMMDq4/dc-tagi1

#    base=$rds/runs/nessy
    base=$rds/runs

#    atm=$rds/cubes/matthias/$ctype/$csnap/$spath
    atm=$rds/cubes/veronika/$stype/$ctype/$csnap/$spath

#    run=veronika/$stype/$ctype/$csnap/$reverse_cube_frac/$rname/$rmode/$rangl
#    run=veronika/$stype/$ctype/$csnap/$rangl
#    run=test_run/$stype/$ctype/$csnap/$rangl
    run=$stype/$ctype/$csnap/$rangl

#    scr=$HOME/nessy/scr
#    obj=$HOME/nessy/obj
#    inp=$HOME/nessy/inp

    nes=$rds/nessy

    scr=$nes/scr
    obj=$nes/obj
    inp=$nes/inp

fi

if [ ! -s $atm/1 ]; then

    echo "Atmospheres not found. Abort."

    exit 1

fi

spec=$base/$run/spec
ncnv=$base/$run/ncnv
fail=$base/$run/fail

declare -i Nx Ny
declare -i i j
declare -i sub
declare -i Nt N_groups Ns Nr
#declare -i ray_number group_number ray_number_in_group

Nx=512
Ny=512

#Nt - total number of rays
#Ns - number of submissions
#N_groups - number of groups in each submission
#Nr - number of rays in each group

if [ $regime == original_run ]; then

    Nt=Nx*Ny

#---------------------------------------------------------

#   full cube, Nr rays per core
    Ns=${N_sub:-1}
    Nr=Nt/N_groups/Ns/reverse_cube_frac

    if ((Nr == 1));  then walltime=04:00:00; fi
    if ((Nr == 2));  then walltime=08:00:00; fi
    if ((Nr == 4));  then walltime=16:00:00; fi
    if ((Nr == 8));  then walltime=32:00:00; fi
    if ((Nr == 16)); then walltime=64:00:00; fi
    if ((Nr == 32)); then walltime=72:00:00; fi

    ws=1800
    we=2990

#---------------------------------------------------------

#   test
#    Ns=2
#    N_groups=2
#    Nr=2

#    walltime=00:31:00

#    ws=1800
#    we=1800
#    we=2990

#---------------------------------------------------------

    N_jobs=' '

    for ((i=1; i<=Ns; i++)); do N_jobs=$N_jobs' '$N_groups; done

    N_jobs=($N_jobs)

    ldo=$rds/logs/nessy/$run/out
    lde=$rds/logs/nessy/$run/err

    slog=$base/$run/success.log
    flog=$base/$run/fail.log

#    mkdir -p $base/$run $ldo $lde
    mkdir -p $base/$run

    if [ -d $base/$run/inp ]; then rm -r $base/$run/inp; fi

    mkdir -p $base/$run/inp

    echo Submitting $run:

    echo Copying input files...

    cp $inp/gen/CARDS.TEMPLATE $base/$run/inp
    cp $inp/gen/cards.inp      $base/$run/inp
    cp $inp/gen/datom.inp      $base/$run/inp
    cp $inp/gen/fgrid.inp      $base/$run/inp
    cp $inp/gen/chem.inp       $base/$run/inp
    cp $inp/gen/fudge.inp      $base/$run/inp
    cp $inp/gen/sun.inp        $base/$run/inp

    ln -s $inp/gen/fort.19.d   $base/$run/inp
    ln -s $inp/gen/odf.inp     $base/$run/inp
    ln -s $inp/gen/fort        $base/$run/inp
    ln -s $inp/gen/crs         $base/$run/inp
    ln -s $inp/gen/mol         $base/$run/inp

    echo Removing old spectra...

    rm -rf $spec

#    for ((i=1; i<=Nx; i++)); do mkdir -p $spec/$i; done

    echo Removing old non-convergence files...

    rm -rf   $ncnv

#    for ((i=1; i<=Nx; i++)); do mkdir -p $ncnv/$i; done

    echo Removing old fail files...

    rm -rf   $fail

#    for ((i=1; i<=Nx; i++)); do mkdir -p $fail/$i; done

    echo Removing old logs...

    rm -f $slog
    rm -f $flog

    rm -rf $ldo
    rm -rf $lde

#    mkdir -p $ldo $lde

    echo "Reverse of the fraction of the cube: $reverse_cube_frac" >  $base/$run/split.log
    echo "Number of submissions:               $Ns"                >> $base/$run/split.log
    echo "Number of groups in each submission: $N_groups"          >> $base/$run/split.log
    echo "Number of rays in each group:        $Nr"                >> $base/$run/split.log

    echo $stype             >  $base/$run/specification.log
    echo $ctype             >> $base/$run/specification.log
    echo $csnap             >> $base/$run/specification.log
    echo $reverse_cube_frac >> $base/$run/specification.log
    echo $rmode             >> $base/$run/specification.log
    echo $rangl             >> $base/$run/specification.log

    cp $obj/hminus.exe       $base/$run
    cp $obj/fioss.exe        $base/$run

    cp $scr/fioss_cplink_dir $base/$run
    cp $scr/fioss_mv_results $base/$run
    cp $scr/fioss_do2        $base/$run

    if [ ! -e $base/$run/spec_to_npz.py ]; then ln -s $nes/pyt/spec_to_npz.py $base/$run; fi

elif [ $regime == housekeeping ]; then

    walltime=24:00:00

    ws=1800
    we=2990

    ldo=$rds/logs/nessy/$run/hk/out
    lde=$rds/logs/nessy/$run/hk/err

    slog=$base/$run/success.hk.log
    flog=$base/$run/fail.hk.log

    rm -f $slog
    rm -f $flog

    echo Removing old logs...

    rm -rf $ldo
    rm -rf $lde

    mkdir -p $fail $ncnv

    declare -i N_remainder

    echo -n "Submitting housekeeping for $run: "

    remaining_rays=' '

    for ((i=1; i<=Nx; i++)); do

        for ((j=1; j<=Ny; j++)); do

#            ray_number=(i-1)*512+j

#            group_number=ray_number/8192+1

#            ray_number_in_group=ray_number%8192

#            if ((ray_number_in_group == 0)); then group_number=group_number-1; fi

            if [[ ! -s $spec/$i/$j ]] && [[ ! -s $ncnv/$i/$j ]] && [[ ! -f $fail/$i/$j ]]; then

#                remaining_rays=$remaining_rays' '$i.$j
                remaining_rays=$remaining_rays' '$i/$j

            fi

        done

    done

    remaining_rays_arr=($remaining_rays)

    Nt=${#remaining_rays_arr[@]}

    if ((Nt == 0)); then

        echo "0 remaining rays."

        exit 0

    fi

    Nr=1

    Ns=Nt/N_groups

    N_jobs=' '

    for ((i=1; i<=Ns; i++)); do N_jobs=$N_jobs' '$N_groups; done

    N_remainder=Nt%N_groups

    if ((N_remainder != 0)); then Ns=Ns+1; N_jobs=$N_jobs' '$N_remainder; fi

    echo "$Nt remaining rays, $Ns submissions."

#    echo $Ns $N_jobs

#    exit 0

    N_jobs=($N_jobs)

#    echo ${N_jobs[@]}

    for ((s=0; s<=Ns-1; s++)); do

        if ((s == 0)); then ids[s]=1; ide[s]=$(echo ${ids[s]}+${N_jobs[s]}-1 | bc); continue; fi

        ids[s]=$(echo ${ids[s-1]}+${N_jobs[s-1]} | bc)

        ide[s]=$(echo ${ids[s]}+${N_jobs[s]}-1 | bc)

    done

#    echo ${ids[@]}
#    echo ${ide[@]}

#    exit 0

else

    echo "Regime not recognized. Abort."

    exit 1

fi

for ((sub=1; sub<=Ns; sub+=1)); do

mkdir -p $ldo/$sub $lde/$sub

#echo ${N_jobs[sub-1]}

if [ $regime == housekeeping ]; then

    hk_rays=' '

    for ((r=${ids[sub-1]}-1; r<=${ide[sub-1]}-1; r++)); do

        hk_rays=$hk_rays' '${remaining_rays_arr[r]}

    done

#    echo $hk_rays

#    exit 0

fi

if [ $host == imperial ]; then

name=n-${ctype:0:1}-$reverse_cube_frac-${rmode:0:1}-$rangl
#name=$pca_mode-${rmode:0:1}

if [ $regime == original_run ]; then name=$name-$sub;    fi
if [ $regime == housekeeping ]; then name=$name-hk-$sub; fi

qsub -v \
host=$host,\
regime=$regime,\
hk_rays="$hk_rays",\
rmode=$rmode,\
base=$base,\
run=$run,\
atm=$atm,\
slog=$slog,\
flog=$flog,\
spec=$spec,\
ncnv=$ncnv,\
fail=$fail,\
reverse_cube_frac=$reverse_cube_frac,\
Ns=$Ns,\
N_groups=$N_groups,\
Nr=$Nr,\
sub=$sub,\
ws=$ws,\
we=$we \
-N $name \
-J 1-${N_jobs[sub-1]}:1 \
-o $ldo/$sub \
-e $lde/$sub \
-lwalltime=$walltime \
-lselect=1:ncpus=1:mem=3gb:avx2=true nessy_calc_ray_spec_hk

elif [ $host == dirac_leicester ]; then

name=${ctype:0:1}/$rangl
#name=n:${ctype:0:1}/$reverse_cube_frac/${rmode:0:1}/$rangl

if [ $regime == original_run ]; then name=$name:$sub;    fi
if [ $regime == housekeeping ]; then name=$name:hk:$sub; fi

qsub -v \
host=$host,\
regime=$regime,\
hk_rays="$hk_rays",\
rmode=$rmode,\
base=$base,\
run=$run,\
atm=$atm,\
slog=$slog,\
flog=$flog,\
spec=$spec,\
ncnv=$ncnv,\
fail=$fail,\
reverse_cube_frac=$reverse_cube_frac,\
Ns=$Ns,\
N_groups=$N_groups,\
Nr=$Nr,\
sub=$sub,\
ws=$ws,\
we=$we \
-A dp100 \
-t 1-${N_jobs[sub-1]} \
-o $ldo/$sub \
-e $lde/$sub \
-N $name \
-l walltime=$walltime,nodes=1:ppn=1,pmem=3gb nessy_calc_ray_spec_hk

elif [ $host == dirac_cambridge ]; then

name=${ctype:0:1}/$rangl

if [ $regime == original_run ]; then name=$name:$sub;    fi
if [ $regime == housekeeping ]; then name=$name:hk:$sub; fi

sbatch \
-A dirac-dp100-cpu \
-p cclake \
--export=host=$host,\
regime=$regime,\
hk_rays="$hk_rays",\
rmode=$rmode,\
base=$base,\
run=$run,\
atm=$atm,\
slog=$slog,\
flog=$flog,\
spec=$spec,\
ncnv=$ncnv,\
fail=$fail,\
reverse_cube_frac=$reverse_cube_frac,\
Ns=$Ns,\
N_groups=$N_groups,\
Nr=$Nr,\
sub=$sub,\
ws=$ws,\
we=$we \
-a 1-${N_jobs[sub-1]}:1 \
-o $ldo/$sub/%A[%a] \
-e $lde/$sub/%A[%a] \
-J $name \
-t $walltime \
-n 1 -c 1 --mem 3gb nessy_calc_ray_spec_hk

fi

done
