#!/bin/bash

#export N_sub=8

#submit_split_cube lte  G2V hydro 123_lte  123_wcr
#submit_split_cube lte  G2V 300G  118_lte  118_wcr

#submit_split_cube nlte G2V hydro 123_nlte 123_wcr
#submit_split_cube nlte G2V 300G  118_nlte 118_wcr

#------------------------------------------------------

#submit_split_cube lte  G2V hydro 123_lte_eh  123_wcr
#submit_split_cube lte  G2V 300G  118_lte_eh  118_wcr

#submit_split_cube nlte G2V hydro 123_nlte_eh 123_wcr
#submit_split_cube nlte G2V 300G  118_nlte_eh 118_wcr

#-------------------------------------------------------

#submit_split_cube nlte G2V hydro 123_nlte_eh 123_wcr

#-------------------------------------------------------

#submit_split_cube lte  G2V ssd 186_lte  186_wcr
#submit_split_cube nlte G2V ssd 186_nlte 186_wcr

#-------------------------------------------------------

#submit_split_cube lte  G2V hydro 123_lte_mu_08  123_wcr_mu_08
#submit_split_cube lte  G2V 300G  118_lte_mu_08  118_wcr_mu_08

#submit_split_cube nlte G2V hydro 123_nlte_mu_08 123_wcr_mu_08
#submit_split_cube nlte G2V 300G  118_nlte_mu_08 118_wcr_mu_08

#------------------------------------------------------

#submit_split_cube G2V hydro 8 angles nlte 6 mu/6
#submit_split_cube G2V 300G  8 angles nlte 6 mu/6

#submit_split_cube G2V hydro 8 angles lte  6 mu/6
#submit_split_cube G2V 300G  8 angles lte  6 mu/6

#submit_split_cube G2V ssd   8 angles nlte 8 mu/8
#submit_split_cube G2V ssd   8 angles nlte 6 mu/6

#submit_split_cube G2V ssd   8 angles lte  8 mu/8
#submit_split_cube G2V ssd   8 angles lte  6 mu/6

#------------------------------------------------------

nessy_submit_split_cube G2V 300G  8 angles lte  2 mu/atms/nessy/2
nessy_submit_split_cube G2V ssd   8 angles lte  2 mu/atms/nessy/2
nessy_submit_split_cube G2V hydro 8 angles lte  2 mu/atms/nessy/2

nessy_submit_split_cube G2V 300G  8 angles nlte 2 mu/atms/nessy/2
nessy_submit_split_cube G2V ssd   8 angles nlte 2 mu/atms/nessy/2
nessy_submit_split_cube G2V hydro 8 angles nlte 2 mu/atms/nessy/2

#------------------------------------------------------

#s=103833

#nessy_submit_split_cube G2V 300G  8 $s lte 2 $s/mu/atms/nessy/2
#nessy_submit_split_cube G2V 300G  8 $s lte 4 $s/mu/atms/nessy/4
#nessy_submit_split_cube G2V 300G  8 $s lte 6 $s/mu/atms/nessy/6
#nessy_submit_split_cube G2V 300G  8 $s lte 8 $s/mu/atms/nessy/8
#nessy_submit_split_cube G2V 300G  8 $s lte 1 $s/mu/atms/nessy/1

#s=251568

#nessy_submit_split_cube G2V ssd   8 $s lte 2 $s/mu/atms/nessy/2
#nessy_submit_split_cube G2V ssd   8 $s lte 4 $s/mu/atms/nessy/4
#nessy_submit_split_cube G2V ssd   8 $s lte 6 $s/mu/atms/nessy/6
#nessy_submit_split_cube G2V ssd   8 $s lte 8 $s/mu/atms/nessy/8
#nessy_submit_split_cube G2V ssd   8 $s lte 1 $s/mu/atms/nessy/1

#s=235427

#nessy_submit_split_cube G2V hydro 8 $s lte 2 $s/mu/atms/nessy/2
#nessy_submit_split_cube G2V hydro 8 $s lte 4 $s/mu/atms/nessy/4
#nessy_submit_split_cube G2V hydro 8 $s lte 6 $s/mu/atms/nessy/6
#nessy_submit_split_cube G2V hydro 8 $s lte 8 $s/mu/atms/nessy/8
#nessy_submit_split_cube G2V hydro 8 $s lte 1 $s/mu/atms/nessy/1
