#!/bin/bash

export N_sub=8

submit_split_cube lte  G2V hydro 123_lte  123_wcr
submit_split_cube lte  G2V 300G  118_lte  118_wcr

submit_split_cube nlte G2V hydro 123_nlte 123_wcr
submit_split_cube nlte G2V 300G  118_nlte 118_wcr

#------------------------------------------------------

#submit_split_cube lte  G2V hydro 123_lte_eh  123_wcr
#submit_split_cube lte  G2V 300G  118_lte_eh  118_wcr

#submit_split_cube nlte G2V hydro 123_nlte_eh 123_wcr
#submit_split_cube nlte G2V 300G  118_nlte_eh 118_wcr

#-------------------------------------------------------

#submit_split_cube nlte G2V hydro 123_nlte_eh 123_wcr
