#!/bin/bash

if [ $# != 2 ]; then
 
   echo Expecting 2 arguments.
 
   exit 1
 
fi

m=$1

form=$2

if [ $form != atlas ] && [ $form != nessy ]; then

    echo "format is not recognized. abort."

    exit 1

fi

dir=$(pwd)

IFS='/' read -r -a array <<< "$dir"

reverse=$(echo "${array[@]} " | tac -s ' ')

r=($reverse)

declare -i n m idx

n=m-1

path=/mnt/SSD/sim/runs/cpline

for i in $(seq 0 $n); do

    idx=n-i

#    echo ${r[idx]}

    path=$path/${r[idx]}

done

#echo $path/atms/$form
echo $path/

#rsync -ar --info=progress2 rtagirov@ph-rtagirov.ph.ic.ac.uk:/mnt/SSD/sim/runs/cpline/${r[2]}/${r[1]}/${r[0]}/atms/ ./
#rsync -ar --info=progress2 rtagirov@ph-rtagirov.ph.ic.ac.uk:$path/atms/$form ./
rsync -ar --info=progress2 rtagirov@ph-rtagirov.ph.ic.ac.uk:$path/ ./
