#!/bin/sh

rm -f logs.out

logs=./*

bold=$(tput bold)
normal=$(tput sgr0)

for log in $logs; do 

    if [[ ! -z $(cat $log) ]]; then 

        echo ${bold}${log}${normal}
        cat $log | tee -a logs.out
#        echo

    fi

done
