#!/bin/sh

logs=$HOME/log/*.ER

bold=$(tput bold)
normal=$(tput sgr0)

for log in $logs; do 

    if [[ ! -z $(cat $log) ]]; then 

        echo ${bold}${log}${normal}
        cat $log
#        echo

    fi

done
