#!/bin/sh

depth=$1

dirs=$(find . -mindepth $depth -maxdepth $depth -type d | sort -V)

for d in $dirs; do

    if [[ ! -f $d/hminus.log ]]; then

        echo $d: no hminus log

        continue

    fi

    conv=$(grep 'MODEL FINALLY CONVERGED' $d/hminus.log)

    if [[ -z $conv ]]; then

        echo $d: hminus fail

        continue

    elif [[ ! -f $d/fioss.log ]]; then

        echo $d: no fioss log

        continue

    fi

    fail=$(grep -i fail $d/fioss.log)

    if [[ ! -z $fail ]]; then

        echo $d: fioss fail 

    fi

done
