#!/bin/sh

#parsed by qsub
#mode
#run

module load intel-suite

scr=$HOME/nessy/scr
inp=$HOME/nessy/inp
obj=$HOME/nessy/obj

base=$HOME/runs/fioss/IT$mode

dir=$base/$run/JOB-1-24228
#dir=$base/$run
tmp=$TMPDIR

cp $base/$run/CARDS.TEMPLATE -t $dir
cp $dir/CARDS.TEMPLATE          $dir/CARDS

echo 'INTERVAL 1800 1810' >> $dir/CARDS

#ln -s $dir/fort.19.d/Kurucz_comb_air_1300to2000.dat $dir/fort.19
ln -s $base/$run/fort.19.d/Kurucz_comb_air_1300to2000.dat $dir/fort.19

cp -r $dir/* -t $tmp

$tmp/fioss.exe | tee $tmp/fioss.out

rsync -rptgoDq $tmp/ $dir/
