#!/bin/sh

depth=$1

declare -i k

dirs=$(find ./ -mindepth $depth -maxdepth $depth -type d | sort -V)

for d in $dirs; do

    echo $d

    if [[ ! -f $d/hminus.log ]] || [[ ! -f $d/fioss.log ]]; then

        continue

    fi

    conv=$(grep 'MODEL FINALLY CONVERGED' $d/hminus.log)
    fail=$(grep -i fail $d/fioss.log)

    if [[ ! -z $conv ]] && [[ -z $fail ]]; then

        subdirs=$(awk -F'/' '{ for(i=1;i<=NF;i++) print $i }' <<< $d)

        hminus=hminus
        fioss=fioss

        k=0

        for subdir in $subdirs; do

           if [[ $k != 0 ]]; then 

                hminus=${hminus}.${subdir}
                fioss=${fioss}.${subdir}

           fi

           k=$k+1

        done

        tail -23 $d/hminus.log | head -3 > ./time/$hminus
        tail -23 $d/fioss.log  | head -3 > ./time/$fioss

    fi

done
