#!/bin/sh

#rm -f $HOME/log/*

mode=$1

if [ "$mode" != "0" ] && [ "$mode" != "1" ]; then echo "mode is not recognized. abort."; exit 1; fi

run=$2
#nums=`seq 11 20`

#for num in $nums; do

#run=time_test/$num

ncpus=1

wt=00:10:00

mem=1gb

qsub -v \
mode=$mode,\
run=$run \
-o $HOME/log/$JOB_ID \
-e $HOME/log/$JOB_ID \
-N $run \
-lwalltime=$wt \
-lselect=1:ncpus=$ncpus:mem=$mem:avx2=true hminus.pbs

#done
