#!/bin/sh

#parsed by qsub
#mode
#run

module load intel-suite

scr=$HOME/nessy/scr
inp=$HOME/nessy/inp
obj=$HOME/nessy/obj

base=$HOME/runs/hminus/IT$mode

#foreach i ( `seq 1 10` )
#foreach i ( 1 2 3 4 5 6 7 8 9 10 )
#for i in `seq 1 10`; do
#for i in $(seq 1 10); do
#set j=`expr "$PBS_ARRAY_INDEX" + "$i"`
#set j=`expr "$PBS_ARRAY_INDEX" + "$i"`

dir=$base/test_batch/$PBS_ARRAY_INDEX
tmp=$TMPDIR

if [ -d "$dir" ]; then rm -r $dir; fi

mkdir -p $dir

ln -s ~/test_batch.exe $dir

cp -r $dir/* -t $tmp

$tmp/test_batch.exe

rsync -rptgoDq $tmp/ $dir/
