#!/bin/sh

rm -f $HOME/log/*

mode=$1

if [ "$mode" != "0" ] && [ "$mode" != "1" ]; then echo "mode is not recognized. abort."; exit 1; fi

#run=$2
#nums=`seq 11 20`

#for num in $nums; do

#run=time_test/$num
#run=test_batch/1

ncpus=1

wt=00:31:00

mem=1gb

#-N $run \
qsub -v mode=$mode \
-J 1-9:1 \
-o $HOME/log/$JOB_ID \
-e $HOME/log/$JOB_ID \
-lwalltime=$wt \
-lselect=1:ncpus=$ncpus:mem=$mem test_job_array.pbs

#done
