C***  changed by Margit Haberreiter

c      PARAMETER ( NVDIM  = 5300, NFMAX=1003, NMAX =1200, NDDD = 75)
c      PARAMETER ( NVDIM  = 8019, NFMAX=1003, NMAX =1200, NDDD = 75)
!       integer,PARAMETER :: NFMAX=1003, NMAX =1200, NDDD = 200
!       integer,PARAMETER :: MFCON  = 2
!       common/opint/OPATOT(NVDIM,NDDD),ETATOT(NVDIM,NDDD),VOPA(NVDIM)
!      &            ,TAU(NFMAX,NMAX),DTAU(NFMAX,NMAX),WTAU(NFMAX,NMAX)
!      &            ,SFINE(NFMAX,NMAX),OPAFINE(NFMAX,NMAX)
!      &            ,XFINE(NMAX),ZFINE(NMAX),SCRAOP(NVDIM)
!       common/oparac/opacon(mfcon,nddd),
!      &              etacon(mfcon,nddd)
! 