      integer,parameter:: MAXATOM = 30 ! DEFINE ARRAY DIMENSIONS
      integer,parameter:: NDIM =  100  ! NUMBER OF LEVELS
      integer,parameter:: NDIMP2 = NDIM + 2
      integer,parameter:: NFDIM = 2000
      integer,parameter:: NFLDIM = 79

      integer,parameter:: NDDIM = 200  ! DEPTH POINTS
      integer,parameter:: NPDIM = 208  ! DEPTH POINTS + 8 ADDITIONAL POINTS
      integer,parameter:: MAXIND = 1000 
      integer,parameter:: MAXHIST = 1
      integer,parameter:: MAXADR = 1


! Achtung: fioss8.for definiert seine eigenen Parameter
