#!/bin/sh

mode=$1

if [ "$mode" != "0" ] && [ "$mode" != "1" ]; then echo "mode is not recognized. abort."; exit 1; fi

run=$2

ncpus=1

#wt=10:00:00
wt=02:00:00

mem=1gb

qsub -v \
mode=$mode,\
run=$run \
-J $3-$4:1 \
-o $HOME/log/$JOB_ID \
-e $HOME/log/$JOB_ID \
-N hydro:$3-$4 \
-lwalltime=$wt \
-lselect=1:ncpus=$ncpus:mem=$mem:avx2=true hminus
