#!/bin/bash
currentDir=$(pwd)
exists=0
for folder in ./fioss/T* ; do         # Use ./* ... NEVER bare *
  if [ -d "$folder" ] ; then   # Check whether file exists.
    echo 'T* subfolders exist, proceeding.'
    exists=1
  fi
  if [ $exists -eq 1 ]; then
    break
  fi
done

if [ ! -d ./subBins ]; then
  echo "subBins folder does not exist, creating ""$(pwd)"/subBins
  mkdir -p ./subBins || exit
fi


for folder in fioss/T*; do(
  echo "Processing ""$folder"
  temperature=$(echo "$folder" | awk -F'/' '{print $( NF )}')
  mkdir -p ./subBins/"$temperature"
  cd subBins/"$temperature" || exit
  python /scratch/cernetic/AtmosphericParameters/mergeAtmospheres.py "$currentDir"/"$folder"/lopa/ /scratch/cernetic/AtmosphericParameters/bins 4 /scratch/cernetic/AtmosphericParameters/subBinsk
) &
done
wait

