#!/bin/bash
#****************************************************************
### VARIABLES
function error_ifunset() {
  ERRVAR=""
  for A in $@; do
    [[ `getVar $A` == "" ]] &&  ERRVAR="$ERRVAR $A"
  done
  [[ $ERRVAR == "" ]] ||  error "Variable(s)$ERRVAR is/are not set"
}

if [[ "$0" =~ '(^-)|(/bin/)bash' ]]; then
  echo "Script must be called, not sourced!"
else
[[ "$COSI_BIN" == "" ]] && echo "Variable COSI_BIN must be set"
source $COSI_BIN/helper_scripts
trap error ERR

source hminus.settings

[[ -e hminus-fioss.settings ]] && source hminus-fioss.settings


THIS_SCRIPT=$0
echo "================= DIRECTORIES ====================
DIR_EXE       = ${DIR_EXE}
DATOM_FILE    = ${DATOM_FILE}
FGRID_FILE    = ${FGRID_FILE}
FALVD_FILE    = ${FALVD_FILE}
CROSS_SECTION_FILES = ${CROSS_SECTION_FILES}
RUN_DIR       = ${RUN_DIR}
OLD           =${OLD}
------- Directory = `pwd` -----------------"
[[ -e ${RUN_DIR} ]] && error "Run Dir already exist"

error_ifunset CROSS_SECTION_FILES DATOM_FILE FGRID_FILE FALVD_FILE RUN_DIR 

mkdir   ${RUN_DIR}
cp        ${ORIG_EXE_FILE}   ${RUN_DIR}/
pushd .
#cd        ${ORIG_SRC}
#tar -czf  ${RUN_DIR}/cosi-src.tgz `find -iname '*.for' ` `find -iname 'Makefile*'`
popd

cp        $THIS_SCRIPT       $RUN_DIR/
cp        hminus.settings    $RUN_DIR
[[ -e hminus-fioss.settings ]] && cp hminus-fioss.settings $RUN_DIR
cd ${RUN_DIR}
echo " ------- Directory = `pwd` -----------------"
pwd
cp ${DATOM_FILE} ./DATOM
cp ${FGRID_FILE} ./FGRID
cp ${FALVD_FILE} ./FAL_VD
cp ${CROSS_SECTION_FILES}/* ./
cp /scratch/shapiroa/Data/Mollist/add/chem.in ./


## If hminus run then
if [[ "" != $LBKG ]]; then
  cp $POPNUM  POPNUM;
  cp $LBKG/*.lbkg .;
  cp $RADIOC  RADIOC;
  cp $RADIOL  RADIOL;
  cp $RADIOCL RADIOCL;
  cp POPNUM OLDMODEL
fi


cat > fort.99 << eof
wrstart
eof
cp ../$OLD/CARDS ./CARDS
if(false); then
cat > CARDS <<  eof
HEADLINE: T=5777K R=1 dM/dt=-11 lgg4.0 T Model "Micha"  with NLTELBKG
ABH=  9.11E-01
ALI=  1.02E-11
ABE=  2.18E-11
ABB=  4.57E-10
ABC=  2.24E-04
ABN=  5.49E-05
ABO=  4.16E-04
ABF=  3.31E-08
ANE=  6.30E-05
ANA=  1.35E-06
AMG=  3.09E-05
AAL=  2.13E-06
ASI=  2.95E-05
ABP=  2.09E-07
ABS=  6.30E-06
ACL=  2.88E-07
AAR=  1.38E-06
ABK=  1.10E-07
ACA=  1.86E-06
ASC=  1.02E-09
ATI=  7.23E-08
ABV=  9.11E-09
ACR=  3.98E-07
AMN=  2.24E-07
AFE=  2.57E-05
ACO=  7.58E-08
ANI=  1.55E-06
ACU=  1.48E-08
AZN=  3.63E-08
ATMEAN= 1.2979378
TABLE
FAL
TEFF=    5777.
RSTAR (SOLAR UNITS):    0.99975
MDOT=   -7.9955
-LINE BLANKETING ON
VELPAR: VFINAL (KM/S)= 1.00  VMIN=4.2E-4BETA= 1. RMAX= 1.01 X
RGRID: ND=56     ND2=TABLEND3= 0.  DLOGTAU= 0.16
NO TEMPERATURE CORRECTION
TMIN=  2000.
VDOP=   5.
LOG G=  4.44          1.
DELTAC=  0.7
GAMMAC=   900.
GAMMAR=   6000.
GAMMAL=   900.
LINE  1 TO LINE 150
JOBMAX=   900.
NEWWRC=   3.
NG
NOACCEL
EPSILON= 0.0001
PRINT HISTORY
PRINT DATOM
PRINT FLUX
eof
fi


if [[ "" != $LBKG ]]; then
cat >> CARDS << eof

LBKG  900 9990
OLDSTART
eof
fi;

cp ../$OLD/*.exe ./
#./hminus.exe | tee model.out
#rm hminus.exe
fi
