#!/usr/bin/env bash

source $scr/aux_func.sh

dir=`pwd`

src=/mnt/SSD/sim/nessy/src
obj=/mnt/SSD/sim/nessy/obj

file=''

ParsedOptions=$(getopt --name "$0" --shell bash --alternative --options "cdov:"\
                --longoptions "comp,ndep,nobj,view:" -- "$@")

if [ $? -ne 0 ]; then 

   abort "Invalid option."

else

   eval set -- "$ParsedOptions"

   while true; do

    case "$1" in

       -c|--comp) compilation=yes;   shift;;

       -d|--ndep) new_deps=yes;      shift;;

       -o|--nobj) new_obj_files=yes; shift;;

       -v|--view) file=$2;           shift 2;;

       --)                           shift; break;;

    esac

   done

fi

if [ "$1" != "hminus" ] && [ "$1" != "fioss" ]; then abort "Invalid argument."; fi

if [ "$compilation" ]; then

   cd $src

   if [ "$new_deps" ]; then ./make/write_deps.sh *.for > ./make/Makefile.deps; fi

   if [ "$new_obj_files" ]; then cd $obj; rm *.mod *.o *.exe; cd $src; fi

   if [ "$1" == "hminus" ]; then

        make hminus

        if [ "$?" -ne 0 ]; then exit 1; fi

   fi

   if [ "$1" == "fioss" ]; then

        make fioss

        if [ "$?" -ne 0 ]; then exit 1; fi

   fi

   cd $dir

   if [ "$1" == "hminus" ]; then cp $obj/hminus.exe ./; fi
   if [ "$1" == "fioss" ];  then cp $obj/fioss.exe  ./; fi

   echo

fi

if [ "$1" == "hminus" ]; then echo wrstart > fort.99; ./hminus.exe | tee hminus.log; fi
if [ "$1" == "fioss" ];  then                         ./fioss.exe |  tee fioss.log;  fi

if [ ! -z ${file} ]; then vim ${file}; fi
