#!/bin/bash
#
echo 'Hello C'
cd ~/data/Asplund_C_final/fioss/IT3_CN
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CN.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000 
echo 'Hello A'
cd ~/data/Asplund_A_final/fioss/IT3_CN
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CN.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello E'
cd ~/data/Asplund_E_final/fioss/IT3_CN
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CN.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello F'
cd ~/data/Asplund_F_final/fioss/IT3_CN
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CN.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello P'
cd ~/data/Asplund_P_final/fioss/IT3_CN
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CN.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello S'
cd ~/data/Asplund_S_NLTE/fioss/IT3_CN
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CN.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello C'
cd ~/data/Asplund_C_final/fioss/IT3_CH
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CH.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello A'
cd ~/data/Asplund_A_final/fioss/IT3_CH
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CH.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello E'
cd ~/data/Asplund_E_final/fioss/IT3_CH
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CH.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello F'
cd ~/data/Asplund_F_final/fioss/IT3_CH
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CH.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello P'
cd ~/data/Asplund_P_final/fioss/IT3_CH
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CH.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000
echo 'Hello S'
cd ~/data/Asplund_S_NLTE/fioss/IT3_CH
cp ~/data/svnroot/cosi/branches/sasha-cosi.my/out-intel-x86_64/fioss8_CH.exe ./fioss8.exe
export MAX_PROC=4
fioss_do2 1000 10 50000

