#!/bin/bash

scr=/mnt/SSD/sim/nessy/scr
inp=/mnt/SSD/sim/nessy/inp
obj=/mnt/SSD/sim/nessy/obj

if [ $# != 4 ]; then

    echo There should be four arguments. Abort.

    exit 0

fi

mode=$1
run=$3
atm=$inp/atm/$4

if [ $mode = lte ];  then fort99=lte;     fi
if [ $mode = nlte ]; then fort99=wrstart; fi

base=/mnt/SSD/sim/runs/nessy

dir=$base/$run

if [ -d "$dir" ]; then rm -r $dir; fi

mkdir -p $dir

ln -s  $base/gen/* $dir

unlink $dir/fort.99
unlink $dir/atm.inp

#--------------------------------------

#unlink $dir/cards.inp

#ln -s $inp/car/atl_ab $dir/cards.inp

#--------------------------------------

ln -s  $atm $dir/atm.inp

ln -s  $scr/fioss_do2        -t $dir
ln -s  $scr/fioss_cplink_dir -t $dir
ln -s  $scr/fioss_mv_results -t $dir

cp     $obj/hminus.exe $dir
cp     $obj/fioss.exe  $dir

cd $dir

echo $fort99 > fort.99

/usr/bin/time -v ./hminus.exe > hminus.log 2>&1 &

wait

conv=$(grep 'MODEL FINALLY CONVERGED' ${dir}/hminus.log)
lte=$(grep 'END OF LTE RUN' ${dir}/hminus.log)

if [[ ! -z $conv ]] || [[ ! -z $lte ]]; then

   export MAX_PROC=$2

   /usr/bin/time -v fioss_do2 1800 10 2990 > fioss.log 2>&1 &

fi
