#!/usr/bin/env bash

dir=`pwd`

src=/mnt/SSD/sim/nessy/src
obj=/mnt/SSD/sim/nessy/obj

file=''

ParsedOptions=$(getopt --name "$0" --shell bash --alternative --options "cdov:"\
                --longoptions "comp,ndep,nobj,view:" -- "$@")

if [ $? -ne 0 ]; then 

   abort "$0: An invalid option has been provided."

else

   eval set -- "$ParsedOptions"

   while true; do

    case "$1" in

       -c|--comp) compilation=yes;   shift;;

       -d|--ndep) new_deps=yes;      shift;;

       -o|--nobj) new_obj_files=yes; shift;;

       -v|--view) file=$2;           shift 2;;

       --)                           shift; break;;

    esac

   done

fi

if [ "$compilation" ]; then

   cd $src

   if [ "$new_deps" ]; then ./make/write_deps.sh *.for > ./make/Makefile.deps; fi

   if [ "$new_obj_files" ]; then cd $obj; rm *.mod *.o *.exe; cd $src; fi

   make hminus

   if [ "$?" -ne 0 ]; then exit 1; fi

   cd $dir

   cp $obj/hminus.exe ./

   echo

fi

echo wrstart > fort.99

./hminus.exe | tee hminus.log

if [ ! -z ${file} ]; then vim ${file}; fi
