      MODULE MOD_PLOTCON
      contains
      SUBROUTINE PLOTCON (KANAL,X,Y,N,ISYMBOL)
      
C**********  MODULNAME: PLOTCON   ******* 24/03/87  19.38.29.******    25 KARTEN
C***  DIESE ROUTINE DIENST ZUM EINTRAGEN EINER 2. ODER 3. FUNKTION IN DEN
C***  BEGONNENEN PLOT ( PLOTCON ) , BZW. AB ENTRY PLOTTAB ZUM EINTRAGEN
C***  DER ERSTEN FUNKTION

      implicit real*8(a-h,o-z)

      DIMENSION X(N),Y(N)
C***  DER FOLGENDE SCHREIBBEFEHL UND DAS ERSTE BACKSPACE SIND NOTWENDIG,
C***  UM EINEN OFFENSICHTLICHEN SYSTEM-FEHLER ZU UEBERLISTEN,
C***  DER ANDERNFALLS DAS BACKSPACE GELEGENTLICH AUF IO TIME LIMIT LAUFEN LAESST
C      WRITE (KANAL,4)
C      BACKSPACE KANAL
C      BACKSPACE KANAL
C      ENTRY PLOTTAB
C*      WRITE (KANAL,1) N,ISYMBOL
C*    1 FORMAT (* N=*,I3,*   PLOTSYMBOL*,I2)
C*      DO 3 I=1,N,5
      DO 3 I=1,N,3
C*      J=MIN0( 5,N-I+1)
      J=MIN0( 3,N-I+1)
C*      WRITE (KANAL,2) (X(I+L-1),L=1,J)
C*      WRITE (KANAL,2) (Y(I+L-1),L=1,J)
      WRITE (KANAL,2) (X(I+L-1),Y(I+L-1),L=1,J)
C*    2 FORMAT (1X, 5(G10.4,2X))
    2 FORMAT (1X, 3(F10.4,F10.5,5X))
    3 CONTINUE
C*      WRITE (KANAL,4)
C*    4 FORMAT (* ENDE*)
      RETURN
      END SUBROUTINE
      END MODULE
